### ISSUE TITLE
[Q&A] Magnetar status and potential release date?

### ISSUE THREAD

**Issue by AlexR00T** [Qata/Magnetar#6]
So im not much aware of swift and how fast they develop as i never worked with it. Id love to know whats the curent status of magnetar and if truly waiting swift 6 having any clue how fast we could expect it out and thus when Magnetar will be out. Are we talking in months or years and years to wait?

**Comment by Qata** [comment]
I can't give a definitive deadline, this is a pet project with some hard technical challenges that I am still unsure how to address. Most of my spare time is currently going to writing a novel, which I'm hoping to have done by mid 2021.

My advice is not to hold your breath on this project, especially while BarMagnet is still functional. My priorities might change if parts of BarMagnet stop working. I'm sorry I can't devote more time to it at the moment.
