### ISSUE TITLE
Synology NAS Testing

### ISSUE THREAD

**Issue by Qata** [Qata/Magnetar#9]
If anyone has a Synology NAS, I would greatly appreciate being able to use it to test out the app.

**Comment by atezanos** [comment]
Hi, I do have one, and I can test the app. Do you mean connecting it against Download Station or transmission app hosted on a Synology NAS?

**Comment by Qata** [comment]
Against Download Station. I'll need access myself as I need to debug it and add new features/support specific to DS.

**Comment by atezanos** [comment]
Ok. I'll create a user so you can test

**Comment by atezanos** [comment]
ready. How can I send you the details privately?

**Comment by Qata** [comment]
lathers.scrape_0d@icloud.com

**Comment by atezanos** [comment]
Any update? have you been able to test?

**Comment by Qata** [comment]
I had querying working but then got sidetracked by moving house. There's gonna be a lot to do, when I can get back to it, as file upload wasn't working even when I followed the spec. (Not surprising, I never got torrent file upload working for BarMagnet, it just converted the torrent file to a magnet link).

Might need to use a dedicated Synology remote app and snoop on its http requests.

**Comment by Qata** [comment]
Good news! I got it working, even torrent file uploads, which even BarMagnet didn't have.
You're good to delete the account you made for me, and I'm hoping to have a useable version by the end of January.
Thank you for the help!

**Comment by atezanos** [comment]
Awesome to hear that. Looking forward to start helping out with alpha/beta testing. As always anything you need let me know. Cheers!
